version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - /root/.acme.sh/:/root/.acme.sh/
      - ./balancer/nginx.conf:/nginx.conf
      - ./balancer/entrypoint.bash:/entrypoint.bash
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    ports:
      - "443:443"
    command: /bin/bash /entrypoint.bash
    restart: always